# Generated by Django 2.0 on 2017-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unidad', models.CharField(choices=[('Miligramos', 'mg'), ('Mililitros', 'ml'), ('Pastillas', 'un'), ('Cajas', 'cajas')], default='Miligramos', max_length=30)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('lote', models.CharField(max_length=50)),
                ('factura', models.CharField(max_length=20)),
                ('fecha_exp', models.DateField()),
                ('costo', models.FloatField()),
            ],
            options={
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Medicinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('unidad_medida', models.CharField(choices=[('Miligramos', 'mg'), ('Mililitros', 'ml'), ('Pastillas', 'un'), ('Cajas', 'cajas')], default='Miligramos', max_length=30)),
                ('linea', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo', models.CharField(max_length=50)),
                ('cantidad_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('codigo_sect', models.CharField(max_length=50)),
                ('aplica_iva', models.BooleanField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('id', 'nombre')},
        ),
    ]
