# Generated by Django 2.0 on 2017-12-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioECUH',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Inventario')),
                ('area', models.CharField(choices=[('EMR', 'Emergencias'), ('UCI', 'Unidad de Cuidados Intensivos'), ('HOS', 'Hospitalizacion'), ('CIR', 'Cirugia')], default='EMR', max_length=30)),
            ],
            options={
                'db_table': 'InventarioECUH',
            },
            bases=('inventario.inventario',),
        ),
        migrations.CreateModel(
            name='InventarioF',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Inventario')),
                ('pvp', models.FloatField()),
                ('precioIVA', models.FloatField()),
            ],
            options={
                'db_table': 'InventarioF',
            },
            bases=('inventario.inventario',),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidad',
            field=models.CharField(choices=[('mg', 'Miligramos'), ('ml', 'Mililitros'), ('unidad', 'Pastillas/unidad'), ('caja', 'Cajas')], default='mg', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicinas',
            name='unidad_medida',
            field=models.CharField(choices=[('Miligramos', 'mg'), ('Mililitros', 'ml'), ('Pastillas', 'un'), ('Cajas', 'cajas')], default='mg', max_length=30),
        ),
    ]
